meta:
  name: (( merge ))
  stemcell: (( merge ))

name: (( grab meta.name ))

director_uuid: (( merge ))

releases: (( merge ))

networks: (( merge ))

jobs: (( merge ))

properties: (( merge ))

compilation:
  workers: 6
  network: smoke_tests1
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: false

resource_pools:
  - name: small_z1
    network: smoke_tests1
    stemcell: (( grab meta.stemcell ))
    cloud_properties: (( merge ))
