meta:
  name: (( param "please provide meta.name" ))
  stemcell: (( param "please provide 'meta.stemcell'" ))

name: (( grab meta.name ))

director_uuid: (( param "please provide 'director_uuid'" ))

releases:
- name: postgresql-smoke-tests
  version: latest

networks: (( param "please provide 'networks'" ))

jobs: (( param "please provide 'jobs'" ))

properties: (( param "please provide 'properties'" ))

compilation:
  workers: 6
  network: smoke_tests1
  reuse_compilation_vms: true
  cloud_properties: (( param "please provide 'compilation.cloud_properties'" ))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: false

resource_pools:
  - name: small_z1
    network: smoke_tests1
    stemcell: (( grab meta.stemcell ))
    cloud_properties: (( param "please provide 'resource_pools.small_z1.cloud_properties'" ))
