meta:
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: smoke_tests
    networks:
      - name: smoke_tests1
        static_ips: ~

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random
    stemcell: (( grab meta.stemcell ))

networks:
- name: smoke_tests1
  type: manual
  subnets: (( grab meta.subnets ))

properties: {}
