update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: smoke_tests
    lifecycle: errand
    templates:
    - name: smoke-tests
      release: postgresql-smoke-tests
    instances: 1
    resource_pool: small_z1
    networks: (( param "please provide smoke_tests networks" ))
    persistent_disk: 10240

networks: (( param "please provide global networks" ))
